spring:
  application:
    name: curbcrime
  datasource:
    driver-class-name: {your database driver}
    url: {your database url}
    username: {your database username}
    password: {your database password}

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true